---
name: Check URLs 🔗

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: links-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  git:
    uses: ./.github/workflows/commit-message.yaml
  links:
    name: Validate Links 🕸️
    runs-on: ubuntu-latest
    if: |
      !(contains(github.event.commits[0].message, '[skip links]') ||
        contains(github.event.head_commit.message, '[skip links]') ||
        contains(needs.git.outputs.msg, '[skip links]')
      )
    steps:
      - name: Checkout repository 🛎
        uses: actions/checkout@v4

      - name: Check URLs in docs 📑
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true
          jobSummary: true
          format: markdown
          output: links-results.md
          args: >-
            --exclude-private
            --exclude "https://github.com.*.git|lycheeverse.*"
            --verbose
            --no-progress
            **/*.md
            **/*.html
            **/*.Rmd
            **/*.yaml
            **/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
