---
name: Check Test Coverage 🧪

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Code Coverage
    uses: pharmaverse/admiralci/.github/workflows/code-coverage.yml@main
    if: >
      github.event_name != 'release'
    with:
      r-version: release
      # Whether to skip code coverage badge creation
      # Setting to 'false' will require you to create
      # an orphan branch called 'badges' in your repository
      skip-coverage-badges: true
